---
- name: Install and Start nginx
  hosts: all
  become: root

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started


# ansible-playbook -i inventory first-playbook.yml (run playbook.yml on main server)
# sudo systemctl status nginx (find if nginx is installed on target servers)
